DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS films;

CREATE TABLE customers (
  id SERIAL PRIMARY KEY,
  name VARCHAR,
  funds DECIMAL(4,2)
);

CREATE TABLE films (
  id SERIAL PRIMARY KEY,
  title VARCHAR,
  price DECIMAL(4,2)
);
